version: "3"

networks:
  tetraka:
    external: true

services:
  server:
    networks:
      - tetraka
    build:
      context: server
      dockerfile: Dockerfile
    environment:
      ENV_NAME: dev
    ports:
      # HOST:CONTAINER or just CONTAINER
      - 5000:5000

  frontend:
    networks:
      - tetraka
    build:
      context: react-ui
      dockerfile: Dockerfile
    environment:
      ENV_NAME: dev
    ports:
      - 3000:80