version: '3.8'

networks: 
  tetraka: {}

services:
  frontend:
    container_name: tetraka-frontend
    build:
      context: react-ui
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      PORT: 5000
    networks: 
      - tetraka
    stdin_open: true