version: '3.8'

services:
  frontend:
    container_name: tetraka-frontend
    build:
      context: react-ui
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      PORT: 5000
      CHOKIDAR_USEPOLLING: "true"
    stdin_open: true
    volumes:
      - './react-ui:/app'
      - '/app/node_modules'

  backend:
    container_name: tetraka-backend
    build: 
      context: server
      dockerfile: Dockerfile
    ports:
      - 8000:5000
    environment:
      PORT: 5000
